FROM ubuntu:16.04

EXPOSE 8000

ADD backend-example-docker /app
WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt install -y nodejs && \
    npm install

CMD ["npm","start"]


