FROM ubuntu:16.04

EXPOSE 5000

ADD frontend-example-docker /app
WORKDIR /app

RUN apt-get update 
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt install -y nodejs
RUN npm install
RUN npm run build
CMD ["npm","start"]


