FROM ubuntu:16.04

EXPOSE 8000

ADD backend-example-docker /app
WORKDIR /app

RUN apt-get update 
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt install -y nodejs

    
RUN npm install

CMD ["npm","start"]


