version: "3"


networks:
   app:

        
services:
  front:
      build:
         context: ../ex_2.03/
         dockerfile: Dockerfile_front
      ports:
          - 8000:5000
      environment:
          - API_URL=http://localhost:8001

  back:
      build:
        context: ../ex_2.03/
        dockerfile: Dockerfile_back
      ports:
          - 8001:8000
      environment:
          - FRONT_URL=http://localhost:8000 
          - REDIS=redis
          - REDIS_PORT=6379
      depends_on:
          - "redis"
      networks:
         - app
      
  redis:
     hostname: redis
     image: redis
     ports:
        - 8010:6379
     networks:
        - app
