version: "3"

services:
  front:
      build:
         context: .
         dockerfile: Dockerfile_front
      ports:
          - 8000:5000
      environment:
          - API_URL=http://localhost:8001
  back:
      build:
        context: .
        dockerfile: Dockerfile_back
      ports:
          - 8001:8000
      environment:
          - FRONT_URL=http://localhost:8000 
